### ISSUE TITLE
wav file parser..

### ISSUE THREAD

**Issue by krs-world** [BridgesUNCC/bridges-cxx#111]
I finally found the issues behind my Wav parser and have pushed updates.. need to do more testing.. to make sure it is bullet proof..

**Comment by esaule** [comment]
You need to push wave.h

Erik

-- 
Dr Erik Saule
Associate Professor at University of North Carolina at Charlotte (UNCC)
tel: +1 (704) 687-8580
web: http://webpages.uncc.edu/~esaule/
== 
Perform academic literature search on http://theadvisor.osu.edu/

**Comment by krs-world** [comment]
Also added a  test (testing repo)  audio_clip2.   That will use the piano sequence. 

Works only for 1 and 2 byte audio  for now. Need to fix the  4 byte  case.

Kyle, do some testing on other sequences..

**Comment by krs-world** [comment]
Pushed wave.h

**Comment by esaule** [comment]
Seems good now.
