### ISSUE TITLE
gutenberg API

### ISSUE THREAD

**Issue by esaule** [BridgesUNCC/bridges-cxx#115]
should be implemented for all types of querys:
get full text
get meta data from ids, title, author, LoC, language, date, genre

And have these properly in the doxygen.

**Comment by krs-world** [comment]
So getting the text needs to return a JSON; this would be better  as it will be more consistent across all queries.  The returned JSON could just contain the text lik
{"book_test": "................."}

or something like that.

**Comment by krs-world** [comment]
Modified to return a dict with book id as key..

**Comment by krs-world** [comment]
this is mostly complete except the caching for full text in Python - assigning to Matthew.

**Comment by esaule** [comment]
this is done in c++ no reason to have that as an issue here
