### ISSUE TITLE
Bar graph support..

### ISSUE THREAD

**Issue by krs-world** [BridgesUNCC/bridges-cxx#139]
This is something that has come up in the past. To expand line charts to support bar graphs. One user was asking about it. WE need to look at it. Assigning to Matthew for us to  discuss next week.

Matthew take a look at it and see what needs to be done - come up with a possible API  and what needs to happen on the server side as well.

**Comment by krs-world** [comment]
C++ barchart has been implemented. Is there an issue?

**Comment by esaule** [comment]
Not entirely sure. The issue is still open and the code has barely no documentation. So I assumed it wasn't done and moved the issue from matthew to you.

**Comment by krs-world** [comment]
You are right on documentation, but the implementation is working. Lets keep this open.

**Comment by esaule** [comment]
done since 33f9387
