### ISSUE TITLE
Inconsistent Documentation

### ISSUE THREAD

**Issue by AnshukGottipati** [BridgesUNCC/bridges-cxx#149]
The addDataSeries Function has the Wrong documentation.

**Comment by esaule** [comment]
Thanks for reorting it.
You are right, this is missing documentation.

**Comment by krs-world** [comment]
This is done. One of you check the documentation and see if its sufficient.

**Comment by esaule** [comment]
That's clearly better! Some more questions:

1/ What are the values we can pass to setBarAlignment?
2/ what are tooltipsuffix?
3/ Is there an underlying assumption that the dataseries data vector must have a length equal to the number of bins?

**Comment by krs-world** [comment]
Hmmm, not sure I have answers all of them, might need to look at the server side code or highcharts..
Will update the docs..

**Comment by krs-world** [comment]
Alignment is eitehr horizontal or vertical.
tooltop suffix can add units or information on the values represented by the bars.
3 -- I suspect yes. I will try to violate the assumption and see what it does!

**Comment by krs-world** [comment]
For 3 - it just adds an additional bar, but no labels are printed.. only tested in C++. So it prints the bar for each data value provided.  On the user to ensure the data he/she provides is valid!

The python version needs to be documented..

**Comment by esaule** [comment]
I think having a random bar is hard to understand. I suggest that we should throw an exception when that happens. That leaves us with only two options:
1/ We throw an exception when adding a new bar that checks that the number of categories are the same as in the axis labels. And also checks that the number of series is zero when changing axis labels. This ensures coherency of the structure. This maintains invariant and so it is good object design. 
2/ When we build the JSON we throw exception if the data is malformed.

What do you all think?

**Comment by krs-world** [comment]
Agreed.

**Comment by esaule** [comment]
fixed since 33f9387
