### ISSUE TITLE
OSM Data API

### ISSUE THREAD

**Issue by squeetus** [BridgesUNCC/bridges-cxx#88]
// OSMData stores vertices, edges arrays and maybe metadata
OSMData <-- getOSMData("Charlotte");

// Graph Adjacency List
graph_al <-- getOSMGraph("Charlotte");

later, we can overload these:

OSMData <-- getOSMData({bounding box});
graph_al <-- getOSMGraph({bounding box});

for large graph representation (>5000 sum of nodes, edges maybe?)
array of vertices, ordered (index), of tuples:  float lat, float long 
array of edges: 1 byte for color, index of v1, index of v2

specify vistype as 'largeGraph' or 'graph-static' or something like that.

**Comment by esaule** [comment]
This seems done since OSM data came online.
