### ISSUE TITLE
graph - bacon number example..

### ISSUE THREAD

**Issue by krs-world** [BridgesUNCC/bridges-cxx#91]
Doesnt render beyond about 1010 nodes (force directed).  Actual data set is 1814. I think we should have a way to set the rendering option, as each has its own benefits now..  See the bacon number example on the bridges website -- you will see some of the clusters disconnected - not the full data set.

**Comment by esaule** [comment]
Should be fixed by the small graph/large graph decision. reopen if the problem still shows.
